spring:
  application:
    name: urlshortener

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    password: ${SPRING_REDIS_PASSWORD}
    ssl: true

app:
  base-url: ${BASE_URL}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true