spring:
  application:
    name: urlshortener

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/urlshortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    ssl: ${SPRING_REDIS_SSL:false}

app:
  base-url: ${BASE_URL:http://localhost:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true